version: '3'

services:
  maven:
    build: .
    volumes:
      - .:/usr/src/mymaven
    command: "tail -f /dev/null"
  tomcat:
    image: tomcat:8-jre8
    ports:
      - "8080:8080"
    volumes: 
      - ./target:/usr/local/tomcat/webapps